name: CI

on:
  pull_request:
  push:
    branches: [main,develop]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Hello
      run: ./hello.sh

  build-push:
    runs-on: ubuntu-latest
    needs: echo
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build & push
      run: docker buildx build --push \
             -t ghcr.io/${{ github.repository }}/hello:${{ github.sha }} .

