name: CI

on:
  pull_request:
  push:
    branches: [main,develop]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Hello
      run: ./hello.sh


